// <auto-generated />
using System;
using Exercise11;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exercise11.Migrations
{
    [DbContext(typeof(AdventureWorksContext))]
    partial class AdventureWorksContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Exercise11.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CustomerID")
                        .HasComment("Primary key.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasComputedColumnSql("(isnull('AW'+[dbo].[ufnLeadingZeros]([CustomerID]),''))", false)
                        .HasComment("Unique number identifying the customer assigned by the accounting system.");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("Date and time the record was last updated.");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int")
                        .HasColumnName("PersonID")
                        .HasComment("Foreign key to Person.BusinessEntityID");

                    b.Property<Guid>("Rowguid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("rowguid")
                        .HasDefaultValueSql("(newid())")
                        .HasComment("ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int")
                        .HasColumnName("StoreID")
                        .HasComment("Foreign key to Store.BusinessEntityID");

                    b.Property<int?>("TerritoryId")
                        .HasColumnType("int")
                        .HasColumnName("TerritoryID")
                        .HasComment("ID of the territory in which the customer is located. Foreign key to SalesTerritory.SalesTerritoryID.");

                    b.HasKey("CustomerId")
                        .HasName("PK_Customer_CustomerID");

                    b.HasIndex("PersonId");

                    b.HasIndex(new[] { "AccountNumber" }, "AK_Customer_AccountNumber")
                        .IsUnique();

                    b.HasIndex(new[] { "Rowguid" }, "AK_Customer_rowguid")
                        .IsUnique();

                    b.HasIndex(new[] { "TerritoryId" }, "IX_Customer_TerritoryID");

                    b.ToTable("Customer", "Sales", t =>
                        {
                            t.HasComment("Current customer information. Also see the Person and Store tables.");
                        });
                });

            modelBuilder.Entity("Exercise11.Employee", b =>
                {
                    b.Property<int>("BusinessEntityId")
                        .HasColumnType("int")
                        .HasColumnName("BusinessEntityID")
                        .HasComment("Primary key for Employee records.  Foreign key to BusinessEntity.BusinessEntityID.");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasComment("Date of birth.");

                    b.Property<bool>("CurrentFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("0 = Inactive, 1 = Active");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .IsFixedLength()
                        .HasComment("M = Male, F = Female");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date")
                        .HasComment("Employee hired on this date.");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Work title such as Buyer or Sales Representative.");

                    b.Property<string>("LoginId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("LoginID")
                        .HasComment("Network login.");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .IsFixedLength()
                        .HasComment("M = Married, S = Single");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("Date and time the record was last updated.");

                    b.Property<string>("NationalIdnumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("NationalIDNumber")
                        .HasComment("Unique national identification number such as a social security number.");

                    b.Property<short?>("OrganizationLevel")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("smallint")
                        .HasComputedColumnSql("([OrganizationNode].[GetLevel]())", false)
                        .HasComment("The depth of the employee in the corporate hierarchy.");

                    b.Property<Guid>("Rowguid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("rowguid")
                        .HasDefaultValueSql("(newid())")
                        .HasComment("ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.");

                    b.Property<bool>("SalariedFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Job classification. 0 = Hourly, not exempt from collective bargaining. 1 = Salaried, exempt from collective bargaining.");

                    b.Property<short>("SickLeaveHours")
                        .HasColumnType("smallint")
                        .HasComment("Number of available sick leave hours.");

                    b.Property<short>("VacationHours")
                        .HasColumnType("smallint")
                        .HasComment("Number of available vacation hours.");

                    b.HasKey("BusinessEntityId")
                        .HasName("PK_Employee_BusinessEntityID");

                    b.HasIndex(new[] { "LoginId" }, "AK_Employee_LoginID")
                        .IsUnique();

                    b.HasIndex(new[] { "NationalIdnumber" }, "AK_Employee_NationalIDNumber")
                        .IsUnique();

                    b.HasIndex(new[] { "Rowguid" }, "AK_Employee_rowguid")
                        .IsUnique();

                    b.ToTable("Employee", "HumanResources", t =>
                        {
                            t.HasComment("Employee information such as salary, department, and title.");

                            t.HasTrigger("dEmployee");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Exercise11.Person", b =>
                {
                    b.Property<int>("BusinessEntityId")
                        .HasColumnType("int")
                        .HasColumnName("BusinessEntityID")
                        .HasComment("Primary key for Person records.");

                    b.Property<string>("AdditionalContactInfo")
                        .HasColumnType("xml")
                        .HasComment("Additional contact information about the person stored in xml format. ");

                    b.Property<string>("Demographics")
                        .HasColumnType("xml")
                        .HasComment("Personal information such as hobbies, and income collected from online shoppers. Used for sales analysis.");

                    b.Property<int>("EmailPromotion")
                        .HasColumnType("int")
                        .HasComment("0 = Contact does not wish to receive e-mail promotions, 1 = Contact does wish to receive e-mail promotions from AdventureWorks, 2 = Contact does wish to receive e-mail promotions from AdventureWorks and selected partners. ");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("First name of the person.");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Last name of the person.");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Middle name or middle initial of the person.");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("Date and time the record was last updated.");

                    b.Property<bool>("NameStyle")
                        .HasColumnType("bit")
                        .HasComment("0 = The data in FirstName and LastName are stored in western style (first name, last name) order.  1 = Eastern style (last name, first name) order.");

                    b.Property<string>("PersonType")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .IsFixedLength()
                        .HasComment("Primary type of person: SC = Store Contact, IN = Individual (retail) customer, SP = Sales person, EM = Employee (non-sales), VC = Vendor contact, GC = General contact");

                    b.Property<Guid>("Rowguid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("rowguid")
                        .HasDefaultValueSql("(newid())")
                        .HasComment("ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.");

                    b.Property<string>("Suffix")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("Surname suffix. For example, Sr. or Jr.");

                    b.Property<string>("Title")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasComment("A courtesy title. For example, Mr. or Ms.");

                    b.HasKey("BusinessEntityId")
                        .HasName("PK_Person_BusinessEntityID");

                    b.HasIndex(new[] { "Rowguid" }, "AK_Person_rowguid")
                        .IsUnique();

                    b.HasIndex(new[] { "LastName", "FirstName", "MiddleName" }, "IX_Person_LastName_FirstName_MiddleName");

                    b.HasIndex(new[] { "AdditionalContactInfo" }, "PXML_Person_AddContact");

                    b.HasIndex(new[] { "Demographics" }, "PXML_Person_Demographics");

                    b.HasIndex(new[] { "Demographics" }, "XMLPATH_Person_Demographics");

                    b.HasIndex(new[] { "Demographics" }, "XMLPROPERTY_Person_Demographics");

                    b.HasIndex(new[] { "Demographics" }, "XMLVALUE_Person_Demographics");

                    b.ToTable("Person", "Person", t =>
                        {
                            t.HasComment("Human beings involved with AdventureWorks: employees, customer contacts, and vendor contacts.");

                            t.HasTrigger("iuPerson");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Exercise11.SalesOrderDetail", b =>
                {
                    b.Property<int>("SalesOrderId")
                        .HasColumnType("int")
                        .HasColumnName("SalesOrderID")
                        .HasComment("Primary key. Foreign key to SalesOrderHeader.SalesOrderID.");

                    b.Property<int>("SalesOrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SalesOrderDetailID")
                        .HasComment("Primary key. One incremental unique number per product sold.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalesOrderDetailId"));

                    b.Property<string>("CarrierTrackingNumber")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasComment("Shipment tracking number supplied by the shipper.");

                    b.Property<decimal>("LineTotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("numeric(38, 6)")
                        .HasComputedColumnSql("(isnull(([UnitPrice]*((1.0)-[UnitPriceDiscount]))*[OrderQty],(0.0)))", false)
                        .HasComment("Per product subtotal. Computed as UnitPrice * (1 - UnitPriceDiscount) * OrderQty.");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("Date and time the record was last updated.");

                    b.Property<short>("OrderQty")
                        .HasColumnType("smallint")
                        .HasComment("Quantity ordered per product.");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID")
                        .HasComment("Product sold to customer. Foreign key to Product.ProductID.");

                    b.Property<Guid>("Rowguid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("rowguid")
                        .HasDefaultValueSql("(newid())")
                        .HasComment("ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.");

                    b.Property<int>("SpecialOfferId")
                        .HasColumnType("int")
                        .HasColumnName("SpecialOfferID")
                        .HasComment("Promotional code. Foreign key to SpecialOffer.SpecialOfferID.");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("money")
                        .HasComment("Selling price of a single product.");

                    b.Property<decimal>("UnitPriceDiscount")
                        .HasColumnType("money")
                        .HasComment("Discount amount.");

                    b.HasKey("SalesOrderId", "SalesOrderDetailId")
                        .HasName("PK_SalesOrderDetail_SalesOrderID_SalesOrderDetailID");

                    b.HasIndex(new[] { "Rowguid" }, "AK_SalesOrderDetail_rowguid")
                        .IsUnique();

                    b.HasIndex(new[] { "ProductId" }, "IX_SalesOrderDetail_ProductID");

                    b.ToTable("SalesOrderDetail", "Sales", t =>
                        {
                            t.HasComment("Individual products associated with a specific sales order. See SalesOrderHeader.");

                            t.HasTrigger("iduSalesOrderDetail");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Exercise11.SalesOrderHeader", b =>
                {
                    b.Property<int>("SalesOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SalesOrderID")
                        .HasComment("Primary key.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalesOrderId"));

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasComment("Financial accounting number reference.");

                    b.Property<int>("BillToAddressId")
                        .HasColumnType("int")
                        .HasColumnName("BillToAddressID")
                        .HasComment("Customer billing address. Foreign key to Address.AddressID.");

                    b.Property<string>("Comment")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("Sales representative comments.");

                    b.Property<string>("CreditCardApprovalCode")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasComment("Approval code provided by the credit card company.");

                    b.Property<int?>("CreditCardId")
                        .HasColumnType("int")
                        .HasColumnName("CreditCardID")
                        .HasComment("Credit card identification number. Foreign key to CreditCard.CreditCardID.");

                    b.Property<int?>("CurrencyRateId")
                        .HasColumnType("int")
                        .HasColumnName("CurrencyRateID")
                        .HasComment("Currency exchange rate used. Foreign key to CurrencyRate.CurrencyRateID.");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID")
                        .HasComment("Customer identification number. Foreign key to Customer.BusinessEntityID.");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime")
                        .HasComment("Date the order is due to the customer.");

                    b.Property<decimal>("Freight")
                        .HasColumnType("money")
                        .HasComment("Shipping cost.");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("Date and time the record was last updated.");

                    b.Property<bool>("OnlineOrderFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("0 = Order placed by sales person. 1 = Order placed online by customer.");

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("Dates the sales order was created.");

                    b.Property<string>("PurchaseOrderNumber")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasComment("Customer purchase order number reference. ");

                    b.Property<byte>("RevisionNumber")
                        .HasColumnType("tinyint")
                        .HasComment("Incremental number to track changes to the sales order over time.");

                    b.Property<Guid>("Rowguid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("rowguid")
                        .HasDefaultValueSql("(newid())")
                        .HasComment("ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.");

                    b.Property<string>("SalesOrderNumber")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasComputedColumnSql("(isnull(N'SO'+CONVERT([nvarchar](23),[SalesOrderID]),N'*** ERROR ***'))", false)
                        .HasComment("Unique sales order identification number.");

                    b.Property<int?>("SalesPersonId")
                        .HasColumnType("int")
                        .HasColumnName("SalesPersonID")
                        .HasComment("Sales person who created the sales order. Foreign key to SalesPerson.BusinessEntityID.");

                    b.Property<DateTime?>("ShipDate")
                        .HasColumnType("datetime")
                        .HasComment("Date the order was shipped to the customer.");

                    b.Property<int>("ShipMethodId")
                        .HasColumnType("int")
                        .HasColumnName("ShipMethodID")
                        .HasComment("Shipping method. Foreign key to ShipMethod.ShipMethodID.");

                    b.Property<int>("ShipToAddressId")
                        .HasColumnType("int")
                        .HasColumnName("ShipToAddressID")
                        .HasComment("Customer shipping address. Foreign key to Address.AddressID.");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasComment("Order current status. 1 = In process; 2 = Approved; 3 = Backordered; 4 = Rejected; 5 = Shipped; 6 = Cancelled");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("money")
                        .HasComment("Sales subtotal. Computed as SUM(SalesOrderDetail.LineTotal)for the appropriate SalesOrderID.");

                    b.Property<decimal>("TaxAmt")
                        .HasColumnType("money")
                        .HasComment("Tax amount.");

                    b.Property<int?>("TerritoryId")
                        .HasColumnType("int")
                        .HasColumnName("TerritoryID")
                        .HasComment("Territory in which the sale was made. Foreign key to SalesTerritory.SalesTerritoryID.");

                    b.Property<decimal>("TotalDue")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("money")
                        .HasComputedColumnSql("(isnull(([SubTotal]+[TaxAmt])+[Freight],(0)))", false)
                        .HasComment("Total due from customer. Computed as Subtotal + TaxAmt + Freight.");

                    b.HasKey("SalesOrderId")
                        .HasName("PK_SalesOrderHeader_SalesOrderID");

                    b.HasIndex("TerritoryId");

                    b.HasIndex(new[] { "SalesOrderNumber" }, "AK_SalesOrderHeader_SalesOrderNumber")
                        .IsUnique();

                    b.HasIndex(new[] { "Rowguid" }, "AK_SalesOrderHeader_rowguid")
                        .IsUnique();

                    b.HasIndex(new[] { "CustomerId" }, "IX_SalesOrderHeader_CustomerID");

                    b.HasIndex(new[] { "SalesPersonId" }, "IX_SalesOrderHeader_SalesPersonID");

                    b.ToTable("SalesOrderHeader", "Sales", t =>
                        {
                            t.HasComment("General sales order information.");

                            t.HasTrigger("uSalesOrderHeader");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Exercise11.SalesPerson", b =>
                {
                    b.Property<int>("BusinessEntityId")
                        .HasColumnType("int")
                        .HasColumnName("BusinessEntityID")
                        .HasComment("Primary key for SalesPerson records. Foreign key to Employee.BusinessEntityID");

                    b.Property<decimal>("Bonus")
                        .HasColumnType("money")
                        .HasComment("Bonus due if quota is met.");

                    b.Property<decimal>("CommissionPct")
                        .HasColumnType("smallmoney")
                        .HasComment("Commision percent received per sale.");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("Date and time the record was last updated.");

                    b.Property<Guid>("Rowguid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("rowguid")
                        .HasDefaultValueSql("(newid())")
                        .HasComment("ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.");

                    b.Property<decimal>("SalesLastYear")
                        .HasColumnType("money")
                        .HasComment("Sales total of previous year.");

                    b.Property<decimal?>("SalesQuota")
                        .HasColumnType("money")
                        .HasComment("Projected yearly sales.");

                    b.Property<decimal>("SalesYtd")
                        .HasColumnType("money")
                        .HasColumnName("SalesYTD")
                        .HasComment("Sales total year to date.");

                    b.Property<int?>("TerritoryId")
                        .HasColumnType("int")
                        .HasColumnName("TerritoryID")
                        .HasComment("Territory currently assigned to. Foreign key to SalesTerritory.SalesTerritoryID.");

                    b.HasKey("BusinessEntityId")
                        .HasName("PK_SalesPerson_BusinessEntityID");

                    b.HasIndex("TerritoryId");

                    b.HasIndex(new[] { "Rowguid" }, "AK_SalesPerson_rowguid")
                        .IsUnique();

                    b.ToTable("SalesPerson", "Sales", t =>
                        {
                            t.HasComment("Sales representative current information.");
                        });
                });

            modelBuilder.Entity("Exercise11.SalesTerritory", b =>
                {
                    b.Property<int>("TerritoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TerritoryID")
                        .HasComment("Primary key for SalesTerritory records.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TerritoryId"));

                    b.Property<decimal>("CostLastYear")
                        .HasColumnType("money")
                        .HasComment("Business costs in the territory the previous year.");

                    b.Property<decimal>("CostYtd")
                        .HasColumnType("money")
                        .HasColumnName("CostYTD")
                        .HasComment("Business costs in the territory year to date.");

                    b.Property<string>("CountryRegionCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasComment("ISO standard country or region code. Foreign key to CountryRegion.CountryRegionCode. ");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Geographic area to which the sales territory belong.");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("Date and time the record was last updated.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Sales territory description");

                    b.Property<Guid>("Rowguid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("rowguid")
                        .HasDefaultValueSql("(newid())")
                        .HasComment("ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.");

                    b.Property<decimal>("SalesLastYear")
                        .HasColumnType("money")
                        .HasComment("Sales in the territory the previous year.");

                    b.Property<decimal>("SalesYtd")
                        .HasColumnType("money")
                        .HasColumnName("SalesYTD")
                        .HasComment("Sales in the territory year to date.");

                    b.HasKey("TerritoryId")
                        .HasName("PK_SalesTerritory_TerritoryID");

                    b.HasIndex(new[] { "Name" }, "AK_SalesTerritory_Name")
                        .IsUnique();

                    b.HasIndex(new[] { "Rowguid" }, "AK_SalesTerritory_rowguid")
                        .IsUnique();

                    b.ToTable("SalesTerritory", "Sales", t =>
                        {
                            t.HasComment("Sales territory lookup table.");
                        });
                });

            modelBuilder.Entity("Exercise11.SalesTerritoryHistory", b =>
                {
                    b.Property<int>("BusinessEntityId")
                        .HasColumnType("int")
                        .HasColumnName("BusinessEntityID")
                        .HasComment("Primary key. The sales rep.  Foreign key to SalesPerson.BusinessEntityID.");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime")
                        .HasComment("Primary key. Date the sales representive started work in the territory.");

                    b.Property<int>("TerritoryId")
                        .HasColumnType("int")
                        .HasColumnName("TerritoryID")
                        .HasComment("Primary key. Territory identification number. Foreign key to SalesTerritory.SalesTerritoryID.");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime")
                        .HasComment("Date the sales representative left work in the territory.");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("Date and time the record was last updated.");

                    b.Property<Guid>("Rowguid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("rowguid")
                        .HasDefaultValueSql("(newid())")
                        .HasComment("ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.");

                    b.HasKey("BusinessEntityId", "StartDate", "TerritoryId")
                        .HasName("PK_SalesTerritoryHistory_BusinessEntityID_StartDate_TerritoryID");

                    b.HasIndex("TerritoryId");

                    b.HasIndex(new[] { "Rowguid" }, "AK_SalesTerritoryHistory_rowguid")
                        .IsUnique();

                    b.ToTable("SalesTerritoryHistory", "Sales", t =>
                        {
                            t.HasComment("Sales representative transfers to other sales territories.");
                        });
                });

            modelBuilder.Entity("Exercise11.Customer", b =>
                {
                    b.HasOne("Exercise11.Person", "Person")
                        .WithMany("Customers")
                        .HasForeignKey("PersonId");

                    b.HasOne("Exercise11.SalesTerritory", "Territory")
                        .WithMany("Customers")
                        .HasForeignKey("TerritoryId");

                    b.Navigation("Person");

                    b.Navigation("Territory");
                });

            modelBuilder.Entity("Exercise11.Employee", b =>
                {
                    b.HasOne("Exercise11.Person", "BusinessEntity")
                        .WithOne("Employee")
                        .HasForeignKey("Exercise11.Employee", "BusinessEntityId")
                        .IsRequired();

                    b.Navigation("BusinessEntity");
                });

            modelBuilder.Entity("Exercise11.SalesOrderDetail", b =>
                {
                    b.HasOne("Exercise11.SalesOrderHeader", "SalesOrder")
                        .WithMany("SalesOrderDetails")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("Exercise11.SalesOrderHeader", b =>
                {
                    b.HasOne("Exercise11.Customer", "Customer")
                        .WithMany("SalesOrderHeaders")
                        .HasForeignKey("CustomerId")
                        .IsRequired();

                    b.HasOne("Exercise11.SalesPerson", "SalesPerson")
                        .WithMany("SalesOrderHeaders")
                        .HasForeignKey("SalesPersonId");

                    b.HasOne("Exercise11.SalesTerritory", "Territory")
                        .WithMany("SalesOrderHeaders")
                        .HasForeignKey("TerritoryId");

                    b.Navigation("Customer");

                    b.Navigation("SalesPerson");

                    b.Navigation("Territory");
                });

            modelBuilder.Entity("Exercise11.SalesPerson", b =>
                {
                    b.HasOne("Exercise11.Employee", "BusinessEntity")
                        .WithOne("SalesPerson")
                        .HasForeignKey("Exercise11.SalesPerson", "BusinessEntityId")
                        .IsRequired();

                    b.HasOne("Exercise11.SalesTerritory", "Territory")
                        .WithMany("SalesPeople")
                        .HasForeignKey("TerritoryId");

                    b.Navigation("BusinessEntity");

                    b.Navigation("Territory");
                });

            modelBuilder.Entity("Exercise11.SalesTerritoryHistory", b =>
                {
                    b.HasOne("Exercise11.SalesPerson", "BusinessEntity")
                        .WithMany("SalesTerritoryHistories")
                        .HasForeignKey("BusinessEntityId")
                        .IsRequired();

                    b.HasOne("Exercise11.SalesTerritory", "Territory")
                        .WithMany("SalesTerritoryHistories")
                        .HasForeignKey("TerritoryId")
                        .IsRequired();

                    b.Navigation("BusinessEntity");

                    b.Navigation("Territory");
                });

            modelBuilder.Entity("Exercise11.Customer", b =>
                {
                    b.Navigation("SalesOrderHeaders");
                });

            modelBuilder.Entity("Exercise11.Employee", b =>
                {
                    b.Navigation("SalesPerson");
                });

            modelBuilder.Entity("Exercise11.Person", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Exercise11.SalesOrderHeader", b =>
                {
                    b.Navigation("SalesOrderDetails");
                });

            modelBuilder.Entity("Exercise11.SalesPerson", b =>
                {
                    b.Navigation("SalesOrderHeaders");

                    b.Navigation("SalesTerritoryHistories");
                });

            modelBuilder.Entity("Exercise11.SalesTerritory", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("SalesOrderHeaders");

                    b.Navigation("SalesPeople");

                    b.Navigation("SalesTerritoryHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
