// <auto-generated />
using Books;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Books.Migrations
{
    [DbContext(typeof(BookContext))]
    partial class BookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Books.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            FirstName = "Paul",
                            LastName = "Deitel"
                        },
                        new
                        {
                            AuthorId = 2,
                            FirstName = "Harvey",
                            LastName = "Deitel"
                        },
                        new
                        {
                            AuthorId = 3,
                            FirstName = "Abbey",
                            LastName = "Deitel"
                        },
                        new
                        {
                            AuthorId = 4,
                            FirstName = "Sue",
                            LastName = "Black"
                        },
                        new
                        {
                            AuthorId = 5,
                            FirstName = "John",
                            LastName = "Purple"
                        },
                        new
                        {
                            AuthorId = 6,
                            FirstName = "Tim",
                            LastName = "Brown"
                        });
                });

            modelBuilder.Entity("Books.AuthorTitle", b =>
                {
                    b.Property<string>("ISBN")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.HasKey("ISBN", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("AuthorTitles");

                    b.HasData(
                        new
                        {
                            ISBN = "132151006",
                            AuthorId = 1
                        },
                        new
                        {
                            ISBN = "132575655",
                            AuthorId = 1
                        },
                        new
                        {
                            ISBN = "133406954",
                            AuthorId = 1
                        },
                        new
                        {
                            ISBN = "133807800",
                            AuthorId = 1
                        },
                        new
                        {
                            ISBN = "133965260",
                            AuthorId = 1
                        },
                        new
                        {
                            ISBN = "133976890",
                            AuthorId = 1
                        },
                        new
                        {
                            ISBN = "134021363",
                            AuthorId = 1
                        },
                        new
                        {
                            ISBN = "134289366",
                            AuthorId = 1
                        },
                        new
                        {
                            ISBN = "134444302",
                            AuthorId = 1
                        },
                        new
                        {
                            ISBN = "134448235",
                            AuthorId = 1
                        },
                        new
                        {
                            ISBN = "134601548",
                            AuthorId = 1
                        },
                        new
                        {
                            ISBN = "132151006",
                            AuthorId = 2
                        },
                        new
                        {
                            ISBN = "132575655",
                            AuthorId = 2
                        },
                        new
                        {
                            ISBN = "133406954",
                            AuthorId = 2
                        },
                        new
                        {
                            ISBN = "133807800",
                            AuthorId = 2
                        },
                        new
                        {
                            ISBN = "133965260",
                            AuthorId = 2
                        },
                        new
                        {
                            ISBN = "133976890",
                            AuthorId = 2
                        },
                        new
                        {
                            ISBN = "134021363",
                            AuthorId = 2
                        },
                        new
                        {
                            ISBN = "134289366",
                            AuthorId = 2
                        },
                        new
                        {
                            ISBN = "134444302",
                            AuthorId = 2
                        },
                        new
                        {
                            ISBN = "134448235",
                            AuthorId = 2
                        },
                        new
                        {
                            ISBN = "134448235",
                            AuthorId = 3
                        },
                        new
                        {
                            ISBN = "133406954",
                            AuthorId = 3
                        },
                        new
                        {
                            ISBN = "134289366",
                            AuthorId = 4
                        });
                });

            modelBuilder.Entity("Books.Title", b =>
                {
                    b.Property<string>("ISBN")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Edition")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ISBN");

                    b.ToTable("Titles");

                    b.HasData(
                        new
                        {
                            ISBN = "132151006",
                            BookTitle = "Internet & World Wide Web How to Program",
                            Edition = 1,
                            Year = 2025
                        },
                        new
                        {
                            ISBN = "132575655",
                            BookTitle = "Java How to Program, Late Objects Version",
                            Edition = 1,
                            Year = 2025
                        },
                        new
                        {
                            ISBN = "133406954",
                            BookTitle = "Visual Basic 2012 How to Program",
                            Edition = 1,
                            Year = 2025
                        },
                        new
                        {
                            ISBN = "133807800",
                            BookTitle = "Java How to Program",
                            Edition = 1,
                            Year = 2025
                        },
                        new
                        {
                            ISBN = "133965260",
                            BookTitle = "iOS 8 for Programmers: An App-Driven Approach with Swift",
                            Edition = 1,
                            Year = 2025
                        },
                        new
                        {
                            ISBN = "133976890",
                            BookTitle = "C How to Program",
                            Edition = 1,
                            Year = 2025
                        },
                        new
                        {
                            ISBN = "134021363",
                            BookTitle = "Swift for Programmers",
                            Edition = 1,
                            Year = 2025
                        },
                        new
                        {
                            ISBN = "134289366",
                            BookTitle = "Android 6 for Programmers: An App-Driven Approach",
                            Edition = 1,
                            Year = 2025
                        },
                        new
                        {
                            ISBN = "134444302",
                            BookTitle = "Android How to Program",
                            Edition = 1,
                            Year = 2025
                        },
                        new
                        {
                            ISBN = "134448235",
                            BookTitle = "C++ How to Program",
                            Edition = 1,
                            Year = 2025
                        },
                        new
                        {
                            ISBN = "134601548",
                            BookTitle = "Visual C# How to Program",
                            Edition = 1,
                            Year = 2025
                        });
                });

            modelBuilder.Entity("Books.AuthorTitle", b =>
                {
                    b.HasOne("Books.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Books.Title", "Title")
                        .WithMany()
                        .HasForeignKey("ISBN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Title");
                });
#pragma warning restore 612, 618
        }
    }
}
